name: Global workflow to rule them all

on:
  push:
      branches: [ main ] #or main

jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Replicating global workflow
          uses: BhagyashreeJoshi821/practice@main
          with:
            github_token: ${{ secrets.CUSTOM_TOKEN }}
            patterns_to_include: '.github/workflows'
            destination_repo: practice2
            exclude_private: true
            exclude_forked: true
            branches: main
            committer_username: BhagyashreeJoshi821
            committer_email: bhagyajoshi96@gmail.com
            commit_message: "ci: update global workflows"
