name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main
  
jobs:
  call-workflow:
    uses: BhagyashreeJoshi821/practice/.github/workflows/callerWorkflow.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: BhagyashreeJoshi821/practice/.github/workflows/calledWorkflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
