name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: BhagyashreeJoshi821/practice/.github/workflows/checkout.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: BhagyashreeJoshi821/practice/.github/workflows/calledWorkflow.yml@main
    with:
        source_file: 'test.txt'
        destination_repo: 'BhagyashreeJoshi821/practice2'
        destination_folder: 'test-dir'
        user_email: 'bhagyajoshi96@gmail.com'
        user_name: 'BhagyashreeJoshi821'
        commit_message: 'Push is successful'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
