name: copy-paste file from one repo to other

on:

  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/copy-file-to-other-repo.yml'
      
concurrency: copy-paste
    
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           path: 'practice'
           ref: 'main'
           persist-credentials: false
           
      - name: Checkout
        uses: actions/checkout@v3
        with:
           path: 'practice2'
           ref: 'main'
           repository: 'practice2/test-dir'
           token: $ {{ secrets.BOT_TOKEN }}
           fetch-depth: 0
           persist-credentials: true
           
      - name: Copy common files to new repo
        shell: bash
        run: |
           mkdir -p practice2/test-dir/charts/ingestion/crds
           cp -rVT practice/manifests/ practice2/test-dir/charts/ingestion/crds
      - name: Check for new files
        id: newFiles
        shell: bash 
        working-directory: practice2
        run: |
           git add -A
           git staus --porcelain | wc -1
           if [[ $(git status --porcelain | wc -1)
             echo "::set-output name=hasNewFiles::false"
           else
             echo "::set-output name=hasNewFiles::false"
           fi
      - name: Push new files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true'}}
        shell: bash
        working-directory: practice2
        run: |
          git config --global --add url."git@github.com:"
          git config --global user.name "BhagyashreeJoshi821"
          git config --global user.email "${{secrets.BOT_EMAIL}}"
          git commit -m "successful"
          git push
           
        

