name: copy file from one repo to other

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: copy file
        uses: BhagyashreeJoshi821/practice@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-file: 'test.txt'
          destination-github-username: 'Bhagyashreejoshi831'
          destination-repository-name: 'practice2'
          user-email: bhagyajoshi96@gmail.com
