name: Call a reusable workflow

on:
  push:
    branches:
      - main
  
jobs:
  call-workflow:
    uses: BhagyashreeJoshi821/practice/.github/workflows/one.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: BhagyashreeJoshi821/practice/.github/workflows/two.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
