name: Call a reusable workflow

on:
  push:
    branches:
      - main
  
jobs:
  call-workflow:
    uses: BhagyashreeJoshi821/practice/.github/workflows/one3.yml@main
    
    
  call-workflow-passing-data:
    uses: BhagyashreeJoshi821/practice/.github/workflows/two.yml@main
    with:
        source_file: 'test.txt'
        destination_repo: 'BhagyashreeJoshi821/practice2'
        destination_folder: 'test-dir'
        user_email: 'bhagyajoshi96@gmail.com'
        user_name: 'BhagyashreeJoshi821'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
