name: Push File

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
        source_file: ${{ inputs.source-file }}
        destination_repo: ${{ inputs.destination-repo }}
        destination_folder: ${{ inputs.destination-folder }}
        user_email: ${{ inputs.user-email }}
        user_name: ${{ inputs.user-name }}
            
 
