name: Push File

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      source_file:
        description: 'Source file from the origin directory'
        required: true
        type: string
      destination_repo:
        description: 'Destination repository'
        required: true
        type: string
      destination_folder:
        description: 'Directory to push the file to'
        required: true
        type: string
      user_email:
        description: 'Email for the git commit'
        required: true
        type: string
      user_name:
        description: 'GitHub username for the commit'
        required: true
        type: string  
    secrets:
      token:
        required: true


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
        source_file: ${{ inputs.source-file }}
        destination_repo: ${{ inputs.destination-repo }}
        destination_folder: ${{ inputs.destination-folder }}
        user_email: ${{ inputs.user-email }}
        user_name: ${{ inputs.user-name }}
            
 
